"""Built-in runtime configuration key registry."""

from __future__ import annotations

from taskweavn.runtime_config.models import RuntimeConfigKey
from taskweavn.runtime_config.registry import RuntimeConfigRegistry


def default_runtime_config_keys() -> tuple[RuntimeConfigKey, ...]:
    """Return the first-batch runtime configuration keys.

    The first batch is intentionally small and behavior-preserving. It records
    values already present in the runtime so diagnostics can explain current
    behavior before write APIs or broader constructor migration exist.
    """

    return (
        RuntimeConfigKey(
            key="agent_loop.default_max_steps",
            domain="agent_loop",
            value_type="int",
            default_value=20,
            scope_levels=("workspace", "session", "agent_run"),
            mutability="next_agent_run",
            source_hints=("built_in_default", "cli", "process_input"),
            description="Maximum AgentLoop ReAct iterations before stopping.",
        ),
        RuntimeConfigKey(
            key="context_manager.checkpoint_interval_steps",
            domain="context_manager",
            value_type="int",
            default_value=5,
            scope_levels=("workspace", "session", "agent_run"),
            mutability="next_agent_run",
            source_hints=("built_in_default", "process_input"),
            description="Agent loop step interval for checkpoint context rendering.",
        ),
        RuntimeConfigKey(
            key="context_manager.max_prior_messages",
            domain="context_manager",
            value_type="int",
            default_value=200,
            scope_levels=("workspace", "session", "agent_run"),
            mutability="next_agent_run",
            source_hints=("built_in_default", "process_input"),
            description="Maximum prior loop messages passed into context assembly.",
        ),
        RuntimeConfigKey(
            key="context_manager.budget.max_events",
            domain="context_manager",
            value_type="int",
            default_value=20,
            scope_levels=("workspace", "session", "task"),
            mutability="next_context_build",
            source_hints=("built_in_default", "process_input"),
            description="Maximum recent event summaries selected for context.",
        ),
        RuntimeConfigKey(
            key="context_manager.budget.max_tool_results",
            domain="context_manager",
            value_type="int",
            default_value=10,
            scope_levels=("workspace", "session", "task"),
            mutability="next_context_build",
            source_hints=("built_in_default", "process_input"),
            description="Maximum recent tool result summaries selected for context.",
        ),
        RuntimeConfigKey(
            key="context_manager.budget.max_file_snippets",
            domain="context_manager",
            value_type="int",
            default_value=6,
            scope_levels=("workspace", "session", "task"),
            mutability="next_context_build",
            source_hints=("built_in_default", "process_input"),
            description="Maximum file snippets selected for context.",
        ),
        RuntimeConfigKey(
            key="context_manager.budget.max_file_snippet_chars",
            domain="context_manager",
            value_type="int",
            default_value=8_000,
            scope_levels=("workspace", "session", "task"),
            mutability="next_context_build",
            source_hints=("built_in_default", "process_input"),
            description="Maximum characters selected for one file snippet.",
        ),
        RuntimeConfigKey(
            key="context_manager.budget.max_rendered_chars",
            domain="context_manager",
            value_type="int",
            default_value=60_000,
            scope_levels=("workspace", "session", "task"),
            mutability="next_context_build",
            source_hints=("built_in_default", "process_input"),
            description="Maximum rendered context characters before compaction pressure.",
        ),
        RuntimeConfigKey(
            key="execution_dispatcher.enabled",
            domain="execution_dispatcher",
            value_type="bool",
            default_value=True,
            scope_levels=("process", "workspace"),
            mutability="startup_only",
            source_hints=("built_in_default", "process_input"),
            restart_required=True,
            description="Whether fixed-route task dispatch is enabled.",
        ),
        RuntimeConfigKey(
            key="execution_dispatcher.max_ticks_per_trigger",
            domain="execution_dispatcher",
            value_type="int",
            default_value=10,
            scope_levels=("process", "workspace"),
            mutability="next_task",
            source_hints=("built_in_default", "process_input"),
            description="Maximum dispatcher ticks per trigger.",
        ),
        RuntimeConfigKey(
            key="task_api.enabled",
            domain="task_api",
            value_type="bool",
            default_value=True,
            scope_levels=("process", "workspace"),
            mutability="startup_only",
            source_hints=("built_in_default", "process_input"),
            restart_required=True,
            description="Whether the local Execution Plane Task API is exposed.",
        ),
        RuntimeConfigKey(
            key="task_api.require_valid_session",
            domain="task_api",
            value_type="bool",
            default_value=True,
            scope_levels=("workspace",),
            mutability="next_task",
            source_hints=("built_in_default", "process_input"),
            description="Whether Task API requests must reference an existing session.",
        ),
        RuntimeConfigKey(
            key="computer_use.enabled",
            domain="computer_use",
            value_type="bool",
            default_value=False,
            scope_levels=("process", "workspace"),
            mutability="startup_only",
            source_hints=("built_in_default", "environment", "cli", "process_input"),
            restart_required=True,
            description="Whether computer-use tools are available to execution agents.",
        ),
        RuntimeConfigKey(
            key="computer_use.backend",
            domain="computer_use",
            value_type="string",
            default_value="disabled",
            scope_levels=("process",),
            mutability="startup_only",
            source_hints=("built_in_default", "environment", "cli", "process_input"),
            restart_required=True,
            description="Selected computer-use backend: disabled, helper, or macos.",
        ),
        RuntimeConfigKey(
            key="computer_use.helper.endpoint_manifest_path",
            domain="computer_use",
            value_type="string",
            default_value="",
            scope_levels=("process", "workspace"),
            mutability="startup_only",
            source_hints=("built_in_default", "environment", "process_input"),
            restart_required=True,
            description=(
                "Path to the app-control helper endpoint manifest. Used when "
                "computer_use.backend is helper."
            ),
        ),
        RuntimeConfigKey(
            key="computer_use.helper.endpoint",
            domain="computer_use",
            value_type="string",
            default_value="",
            scope_levels=("process",),
            mutability="startup_only",
            source_hints=("built_in_default", "environment", "process_input"),
            restart_required=True,
            description=(
                "Direct app-control helper endpoint override for development."
            ),
        ),
        RuntimeConfigKey(
            key="computer_use.allowed_apps",
            domain="computer_use",
            value_type="string_list",
            default_value=(),
            scope_levels=("process", "workspace"),
            mutability="startup_only",
            source_hints=("built_in_default", "environment", "cli", "process_input"),
            restart_required=True,
            description="Application allowlist for computer-use actions.",
        ),
        RuntimeConfigKey(
            key="computer_use.allow_coordinate_click",
            domain="computer_use",
            value_type="bool",
            default_value=False,
            scope_levels=("process", "workspace"),
            mutability="startup_only",
            source_hints=("built_in_default", "process_input"),
            restart_required=True,
            description="Whether coordinate-based clicks are allowed.",
        ),
        RuntimeConfigKey(
            key="computer_use.screen_recording_required",
            domain="computer_use",
            value_type="bool",
            default_value=False,
            scope_levels=("process", "workspace"),
            mutability="startup_only",
            source_hints=("built_in_default", "process_input"),
            restart_required=True,
            description="Whether the computer-use backend requires screen recording readiness.",
        ),
        RuntimeConfigKey(
            key="computer_use.max_text_chars",
            domain="computer_use",
            value_type="int",
            default_value=4_000,
            scope_levels=("process", "workspace"),
            mutability="startup_only",
            source_hints=("built_in_default", "process_input"),
            restart_required=True,
            description="Maximum text length accepted by computer-use text entry.",
        ),
        RuntimeConfigKey(
            key="safety.high_risk_confirmation",
            domain="safety",
            value_type="string",
            default_value="required",
            scope_levels=("workspace", "session", "task"),
            mutability="next_action",
            source_hints=("built_in_default", "process_input"),
            description="Confirmation policy for high-risk user-visible actions.",
        ),
        RuntimeConfigKey(
            key="llm.default_provider",
            domain="llm",
            value_type="string",
            default_value="deepseek",
            scope_levels=("global", "workspace", "session"),
            mutability="next_llm_call",
            source_hints=("built_in_default", "environment", "settings_store", "cli"),
            description="Default LLM provider for runtime calls.",
        ),
        RuntimeConfigKey(
            key="llm.default_model",
            domain="llm",
            value_type="string",
            default_value="deepseek-v4-pro",
            scope_levels=("global", "workspace", "session"),
            mutability="next_llm_call",
            source_hints=("built_in_default", "environment", "settings_store", "cli"),
            description="Default LLM model identifier.",
        ),
        RuntimeConfigKey(
            key="llm.request_timeout_seconds",
            domain="llm",
            value_type="float",
            default_value=180.0,
            scope_levels=("global", "workspace", "session"),
            mutability="next_llm_call",
            source_hints=("built_in_default", "environment", "settings_store"),
            description="Default LLM request timeout in seconds.",
        ),
        RuntimeConfigKey(
            key="logging.profile",
            domain="logging",
            value_type="string",
            default_value=None,
            scope_levels=("global", "workspace", "session"),
            mutability="live",
            source_hints=("built_in_default", "settings_store", "cli", "process_input"),
            description="Selected structured logging profile.",
        ),
        RuntimeConfigKey(
            key="logging.level",
            domain="logging",
            value_type="string",
            default_value="INFO",
            scope_levels=("global", "workspace", "session"),
            mutability="live",
            source_hints=("built_in_default", "settings_store", "cli", "process_input"),
            description="Default structured logging level.",
        ),
        RuntimeConfigKey(
            key="web.search_enabled",
            domain="web",
            value_type="bool",
            default_value=False,
            scope_levels=("global", "workspace", "session"),
            mutability="next_action",
            source_hints=("built_in_default", "environment", "settings_store"),
            description="Whether web search can be used by runtime tools.",
        ),
        RuntimeConfigKey(
            key="web.fetch_limits",
            domain="web",
            value_type="object",
            default_value={
                "maxUrls": 3,
                "maxCharsPerUrl": 20_000,
                "maxTotalChars": 40_000,
            },
            scope_levels=("global", "workspace", "session"),
            mutability="next_action",
            source_hints=("built_in_default", "environment", "settings_store"),
            description="Default web fetch limits.",
        ),
        RuntimeConfigKey(
            key="read_only_inquiry.llm_enabled",
            domain="read_only_inquiry",
            value_type="bool",
            default_value=True,
            scope_levels=("process", "workspace"),
            mutability="startup_only",
            source_hints=("built_in_default", "environment", "cli", "process_input"),
            restart_required=True,
            description="Whether read-only inquiry can use guarded LLM answers.",
        ),
        RuntimeConfigKey(
            key="runtime_input_router.mode",
            domain="runtime_input_router",
            value_type="string",
            default_value="llm_first",
            scope_levels=("process", "workspace"),
            mutability="startup_only",
            source_hints=("built_in_default", "process_input"),
            restart_required=True,
            description="Runtime Input Router semantic interpreter mode.",
        ),
        RuntimeConfigKey(
            key="runtime_input_router.llm_planner_required",
            domain="runtime_input_router",
            value_type="bool",
            default_value=True,
            scope_levels=("process", "workspace"),
            mutability="startup_only",
            source_hints=("built_in_default", "process_input"),
            restart_required=True,
            description="Whether free-form natural language requires an LLM planner route.",
        ),
        RuntimeConfigKey(
            key="runtime_input_router.planner_failure_policy",
            domain="runtime_input_router",
            value_type="string",
            default_value="fail_closed_no_mutation",
            scope_levels=("process", "workspace"),
            mutability="startup_only",
            source_hints=("built_in_default", "process_input"),
            restart_required=True,
            description="Router behavior when the LLM planner is unavailable or invalid.",
        ),
        RuntimeConfigKey(
            key="runtime_input_router.skill_source",
            domain="runtime_input_router",
            value_type="string",
            default_value="builtin_runtime_skills",
            scope_levels=("process",),
            mutability="startup_only",
            source_hints=("built_in_default", "process_input"),
            restart_required=True,
            description="Source for Router skill instructions injected into planner context.",
        ),
        RuntimeConfigKey(
            key="runtime_input_router.max_skill_instruction_chars",
            domain="runtime_input_router",
            value_type="int",
            default_value=2_400,
            scope_levels=("process",),
            mutability="startup_only",
            source_hints=("built_in_default", "process_input"),
            restart_required=True,
            description="Maximum instruction characters loaded per Router runtime skill.",
        ),
        RuntimeConfigKey(
            key="debug.main_page_trace_enabled",
            domain="debug",
            value_type="bool",
            default_value=True,
            scope_levels=("process",),
            mutability="live",
            source_hints=("built_in_default", "environment", "process_input"),
            description="Whether Main Page trace logging is enabled.",
        ),
        RuntimeConfigKey(
            key="debug.main_page_trace_sink",
            domain="debug",
            value_type="object",
            default_value={
                "print": False,
                "file": None,
            },
            scope_levels=("process",),
            mutability="startup_only",
            source_hints=("built_in_default", "environment", "process_input"),
            restart_required=True,
            description="Main Page trace mirror sinks.",
        ),
    )


def build_default_runtime_config_registry() -> RuntimeConfigRegistry:
    registry = RuntimeConfigRegistry()
    registry.register_many(default_runtime_config_keys())
    return registry


__all__ = [
    "build_default_runtime_config_registry",
    "default_runtime_config_keys",
]
