import type { UiTextCatalog } from "./catalogShape";

export const zhCN: UiTextCatalog = {
  audit: {
    actions: {
      refreshAudit: "刷新审计",
      return: "返回",
      viewAudit: "查看审计",
    },
    detail: {
      actions: {
        backToList: "返回列表",
        openFile: "打开文件",
        viewDiff: "查看 Diff",
      },
      labels: {
        auditRecordDetail: "审计记录详情",
        disclosure: "披露范围",
        effectiveConfiguration: "生效配置",
        evidenceVisibility: "证据可见性",
        hiddenReason: "隐藏原因",
        partialReason: "部分证据原因",
        permissionReason: "权限原因",
        rawPayload: "原始载荷",
        recordPayload: "记录载荷",
        redactionReason: "脱敏原因",
        relatedLogs: "相关日志",
        reservedLinks: "保留链接",
        sanitizedEvidence: "脱敏证据",
        sanitizedEvidencePayload: "脱敏证据载荷",
        sanitizedRecordPayload: "脱敏记录载荷",
        whatHappened: "发生了什么",
        whyItMatters: "为什么重要",
        workspaceEvidence: "工作区证据",
      },
      messages: {
        availableByPolicy: "按策略可用",
        configurationSummaryUnavailable: "配置摘要不可用。",
        evidenceDetailLoadError: ({ message }) => `证据详情加载失败：${message}`,
        evidenceDetailLoading: "正在加载证据详情。",
        evidencePayloadTitle: ({ label }) => `证据载荷 · ${label}`,
        hiddenByDefault: "默认隐藏",
        hiddenByPermission: "因权限隐藏",
        hiddenByPolicy: "因策略隐藏",
        limited: "受限",
        loadingCompleteRecordDetail: "正在加载完整记录详情。",
        noEvidenceForRecord: "此记录暂无可用证据。",
        noPayloadAvailable: "暂无可用载荷",
        noRelatedLogLink: "暂无相关日志链接。",
        noSanitizedPayloadForRecord: "此记录暂无可用脱敏载荷。",
        payloadAvailableNotShown: "载荷可用，未展示",
        recordDetailLoadError: ({ message }) => `记录详情加载失败：${message}`,
        recordEventSummary: ({ kind, source, time }) =>
          `${source} 在 ${time} 记录了 ${kind} 事件。`,
        sanitizedPayloadShown: "已展示脱敏载荷",
        visible: "可见",
      },
    },
    empty: {
      noEvidence: "暂无可用证据。",
    },
    labels: {
      audit: "审计",
      auditEvidenceWorkspace: "审计证据工作区",
      auditOverview: "审计概览",
      auditRecordFilters: "审计记录筛选",
      auditRecords: "审计记录",
      auditVerdictNotice: "审计结论提示",
      auditWorkflow: "审计工作流",
      code: "代码",
      cursor: "游标",
      confidence: ({ value }) => `置信度：${value}`,
      evidenceRefCount: ({ count }) => `${count} 个证据引用`,
      evidenceTimeline: "证据时间线",
      evidence: "证据",
      filter: "筛选",
      filterCountsHelp: "各范围的计数会持续显示。",
      keyIssue: "关键问题",
      noMutations: "无修改",
      project: "项目",
      productSubtitle: "任务优先智能工作台",
      readOnly: "只读",
      recordCount: ({ count }) => `${count} 条记录`,
      recordFilters: "记录筛选",
      resyncSuggested: "建议重新同步",
      retryable: "可重试",
      scope: ({ kind }) => `范围：${kind}`,
      sessionName: ({ name }) => `会话：${name}`,
      session: "会话",
      task: "任务",
      taskAuthoring: "任务编排",
      taskPlanningExecution: "任务规划与执行",
      trustPlane: "信任平面",
      visibleRecords: "可见记录",
    },
    boundary: {
      backend_busy: "后端繁忙",
      empty: "为空",
      fatal_error: "严重错误",
      hidden_evidence: "隐藏证据",
      loading: "加载中",
      partial: "部分证据",
      permission_denied: "权限不足",
      ready: "就绪",
      recoverable_error: "可恢复错误",
      stale_resync: "快照过期",
    },
    completeness: {
      complete: "完整",
      failed: "失败",
      hidden: "隐藏",
      not_started: "未开始",
      partial: "部分",
      running: "运行中",
    },
    filters: {
      actions: "操作",
      all: "全部记录",
      config: "配置",
      confirmations: "确认",
      files: "文件",
      logs: "日志",
      results: "结果",
      risks: "风险",
      system: "系统",
    },
    liveStatus: {
      disconnectedMessage: "仍可手动刷新；此页面可能不会自动更新。",
      disconnectedTitle: "实时审计更新不可用",
      refreshingMessage: "实时审计流正在应用新记录。",
      refreshingTitle: "正在更新审计证据",
      staleMessage: "正在从来源刷新；当前证据仍可读取。",
      staleTitle: "审计快照可能已过期",
    },
    messages: {
      auditRecordEmptyBody: "会话产生审计记录后会显示在这里。",
      auditRecordEmptyTitle: "暂无审计记录",
      evidenceTimelineHelp: "来自事件和消息的用户可读记录。",
      loadingAudit: "正在读取审计记录和证据。",
      permissionLimited: "权限受限",
      readOnlyTrustPlane:
        "审计是只读信任平面。它解释发生了什么，不会修改任务或会话。",
      snapshotUnavailable: "审计快照不可用。",
      unavailable: "审计不可用",
    },
    scopeStatus: ({ kind, status }) => `${kind} 审计 · ${status}`,
    actors: {
      agent: "智能体",
      audit_agent: "审计智能体",
      system: "系统",
      tool: "工具",
      user: "用户",
    },
    confidenceLevels: {
      high: "高",
      low: "低",
      medium: "中",
      unknown: "未知",
    },
    flags: {
      hidden: "已隐藏",
      partial: "部分证据",
      redacted: "已脱敏",
      stale: "可能过期",
    },
    recordKinds: {
      action: "操作",
      audit_verdict: "审计结论",
      config_change: "配置变更",
      confirmation: "确认",
      file_change: "文件变更",
      log_evidence: "日志证据",
      message: "消息",
      observation: "观测",
      result: "结果",
      risk: "风险",
      system: "系统",
    },
    sourceLabels: {
      AuditAgent: "审计智能体",
      EventStream: "事件流",
      "Log archive": "日志归档",
      "Log archive manifest": "日志归档清单",
      Workspace: "工作区",
    },
    verdict: {
      failed: "结论：失败",
      inconclusive: "结论：尚无定论",
      not_available: "结论：不可用",
      passed: "结论：通过",
      warning: "结论：警告",
    },
    verdictNotice: {
      failed: "审计发现阻塞问题。",
      inconclusive: "审计尚无法建立足够信心。",
      warning: "审计发现非阻塞问题。",
    },
  },
  common: {
    actions: {
      cancel: "取消",
      close: "关闭",
      retry: "重试",
    },
    status: {
      creating: "创建中",
      disabled: "已禁用",
      failed: "失败",
      loading: "加载中",
      ready: "就绪",
    },
  },
  diagnostics: {
    actions: {
      exportBundle: "导出诊断",
      returnToAudit: "返回审计",
      returnToSession: "返回会话",
    },
    labels: {
      auditRecord: "审计记录",
      bundle: "诊断包",
      bundleReady: "诊断包已就绪",
      diagnosticExportResult: "诊断导出结果",
      diagnostics: "诊断",
      exportBundle: "导出诊断包",
      manifest: "Manifest",
      readOnly: "只读",
      redaction: "脱敏",
      session: "会话",
      task: "任务",
      zipPath: "Zip 路径",
    },
    messages: {
      contextUnavailable: "此路由缺少诊断上下文。",
      exportBody:
        "为此会话创建已脱敏的本地诊断包，不在 UI 中暴露原始日志。",
      exportFailed: "诊断导出失败。请重试或使用 CLI 命令。",
      fileCount: ({ count }) => `${count} 个文件`,
      handoffReady: "会话日志引用已准备好，可在本地导出。",
      includedSections: ({ sections }) => `包含区段：${sections}。`,
      noSections: "无",
      sidecarRequired: "请使用本地 sidecar 启动 Plato 后再从 UI 导出诊断。",
      warningCount: ({ count }) => `Manifest 中记录了 ${count} 个警告。`,
    },
  },
  main: {
    actions: {
      createSession: "新建会话",
      copySessionId: "复制会话 ID",
      deleteSession: "删除会话",
      newSession: "新建",
      openSession: "打开会话",
      publishPlan: "发布计划",
      renameSession: "重命名会话",
      repairAuthoringState: "修复编排状态",
    },
    empty: {
      createFirstSessionBody: "这个工作区还没有会话。准备开始时创建一个会话。",
      createFirstSessionTitle: "创建第一个会话",
      noPlanBody: "描述一个目标。Plato 会先为你起草任务计划。",
      noPlanTitle: "还没有任务计划",
    },
    input: {
      contextMessageAriaLabel: "上下文消息",
      sendMessageAriaLabel: "发送消息",
      writingToPrefix: "写入",
      writingTo: ({ target }) => `写入${target}`,
    },
    labels: {
      noSessions: "暂无会话",
      noSessionSelected: "未选择会话",
      sessionActions: "会话操作",
      sessionName: ({ name }) => `会话：${name}`,
      taskWorkspace: "任务工作区",
      workspaceSessions: "工作区会话",
    },
    plan: {
      defaultTitle: "任务树",
      generatingBody: "Plato 正在理解你的目标，并组织第一版任务计划。",
      generatingTitle: "正在生成任务计划",
      overviewLabel: "计划概览",
      overviewPrepared: "计划概览正在准备中。",
      overviewSummary: ({ count, remainingCount, titles }) => {
        const suffix = remainingCount > 0 ? `，以及另外 ${remainingCount} 个` : "";
        return `包含 ${count} 个任务的计划，覆盖 ${titles}${suffix}。`;
      },
      taskCount: ({ count }) => `此计划包含 ${count} 个任务`,
    },
    repair: {
      authoringStateNeedsRepair: "编排状态需要修复",
      repairing: "修复中",
    },
    sessionDialog: {
      createFormAriaLabel: "新建会话表单",
      createTitle: "新建会话",
      deleteConfirmationAriaLabel: "删除会话确认",
      deleteConfirmationBody: ({ name }) =>
        `删除会话“${name}”？Plato 会归档此会话，并切换到下一个可用会话。`,
      deleteTitle: "删除会话？",
      deleting: "删除中",
      renameFormAriaLabel: "重命名会话表单",
      renameTitle: "重命名会话",
      renaming: "重命名中",
      sessionName: "会话名称",
    },
    states: {
      creatingSession: "创建中",
      creatingSessionFull: "正在创建会话",
      loadError: "加载失败",
      openingSessionBody: "Plato 正在准备这个工作区。",
      openingSessionTitle: "正在打开会话",
      publishingPlan: "正在发布计划",
      unableToOpenSessionBody: "Plato 无法加载此会话。请刷新页面或选择其他会话。",
      unableToOpenSessionTitle: "无法打开会话",
      workspaceSwitchFailed: "无法打开该工作区。",
      workspaceSwitchUnavailable: "工作区切换只能在 Plato 桌面应用中使用。",
      workspaceSwitching: "正在切换工作区。",
    },
  },
  productError: {
    recoveryAriaLabel: "建议的恢复操作",
    recovery: {
      answer_ask: {
        description: "先回答待处理的问题，再继续。",
        label: "回答问题",
      },
      edit_input: {
        description: "修改输入后再次提交。",
        label: "修改输入",
      },
      export_diagnostics: {
        description: "导出已脱敏的诊断包。",
        label: "导出诊断",
      },
      none: {
        description: "当前没有安全的产品恢复操作。",
        label: "无安全恢复操作",
      },
      open_audit: {
        description: "查看受影响会话或任务的审计证据。",
        label: "查看审计",
      },
      open_settings: {
        description: "打开本地 provider 设置。",
        label: "打开设置",
      },
      refresh_snapshot: {
        description: "刷新会话视图以获取最新状态。",
        label: "刷新会话",
      },
      retry_command: {
        description: "解决问题后再次运行命令。",
        label: "重试命令",
      },
      retry_task: {
        description: "可重试时重新运行受影响的任务。",
        label: "重试任务",
      },
      wait_for_events: {
        description: "等待 sidecar 事件更新后再继续操作。",
        label: "等待更新",
      },
    },
  },
  settings: {
    actions: {
      configureSettings: "配置设置",
      continueToMainPage: "继续进入主页面",
      closeSettings: "关闭设置",
      exportDiagnostics: "导出诊断",
      exportingDiagnostics: "正在导出诊断",
      openSettings: "打开设置",
      retryCheck: "重新检查",
      retryLoad: "重新加载",
      return: "返回",
      saveAndCheck: "保存并检查",
    },
    fields: {
      apiKey: "API 密钥",
      bundle: "诊断包",
      defaultProfile: "默认配置",
      diagnostics: "诊断",
      gitAvailability: "Git 可用性",
      initializeGitForOpenedWorkspaces: "打开工作区时初始化 Git",
      interfaceLanguage: "界面语言",
      logging: "日志",
      loggingProfile: "日志配置",
      model: "模型",
      provider: "服务商",
      readiness: "就绪状态",
    },
    labels: {
      blockingIssues: "阻塞问题",
      checkingSetup: "正在检查设置",
      completeFirstRunSetup: "完成首次运行设置",
      configured: "已配置",
      degradedReady: "本地设置已就绪，但存在警告。",
      diagnosticsAvailable: "诊断包导出可用",
      diagnosticsUnavailable: "诊断包导出不可用",
      editable: "可编辑",
      firstRun: "首次运行",
      firstRunReady: "首次运行设置已就绪。",
      gitAvailable: "Git 可用",
      gitFailed: "Git 检查失败",
      gitMissing: "未找到 Git",
      localSetup: "本地设置",
      missing: "缺失",
      missingEnvironmentVariables: "缺失的环境变量",
      noDiagnosticSession: "当前还没有可用于导出诊断的会话。",
      notChecked: "未检查",
      notCreated: "未创建",
      readinessIssues: "就绪问题",
      readinessResult: "就绪结果",
      recommendedActions: "建议操作",
      setupCheckUnavailable: "无法检查设置",
      setupRequired: "需要完成设置",
      setupWarning: "设置警告",
      settings: "设置",
      settingsSetupForm: "设置配置表单",
      settingsUnavailable: "设置不可用",
      sidecarRequired: "需要 sidecar",
      warnings: "警告",
      workspaceGit: "工作区 Git",
      zipPath: "Zip 路径",
    },
    messages: {
      apiKeyConfigured: ({ source }) =>
        `已通过 ${source} 配置；留空可保持不变。`,
      apiKeyRequired: ({ hint }) => `必填：${hint}。`,
      checkingReadiness: "正在检查就绪状态。",
      checkingSidecarReadiness: "正在检查本地 sidecar 就绪状态。",
      checkingGitAvailability: "正在检查 Git 可用性。",
      diagnosticExportFailed: "诊断导出失败。",
      diagnosticExportHelp:
        "当设置仍失败且已有会话时，导出已脱敏的本地诊断包。",
      gitAvailable: ({ version }) =>
        `Git 可用：${version.replace(/^git version\s*/iu, "")}`,
      gitFailedHelp: "Plato 无法确认此设备上的 Git 是否可用。",
      gitMissingHelp: "安装 Git 后才能为新打开的工作区自动初始化仓库。",
      initializeGitForOpenedWorkspacesHelp:
        "开启后，Plato 会在打开或切换到普通文件夹时运行 git init，并把 .plato/ 写入仓库本地排除文件。",
      loadingSettings: "正在加载设置",
      loadingSettingsHelp: "正在加载本地 sidecar 设置。",
      localSetupReadyWithWarnings: "本地设置已就绪，但存在警告。",
      noReadinessReport: "本地 sidecar 未返回就绪报告。",
      noDiagnosticSession: "当前还没有可用于导出诊断的会话。",
      readinessRecheckFailed: "就绪状态重新检查失败。",
      saveFailed: "设置保存失败。",
      saved: "设置已保存。",
      saving: "正在保存设置。",
      settingsContractUnavailable: "本地 sidecar 未返回设置配置合同。",
      settingsDescription: "配置 Product 1.0 工作流使用的本地 LLM 设置。",
      settingsUnavailableHelp:
        "请以本地 sidecar HTTP 模式启动 Plato 后再编辑 Product 1.0 设置。",
      setupRequiredBody:
        "Plato 需要本地 LLM 配置后才能运行主页面工作流。",
      workspaceGitDesktopUnavailable:
        "工作区 Git 初始化仅在 Plato 桌面应用中可用。",
    },
    localeOptions: {
      "en-US": "English",
      "zh-CN": "简体中文",
    },
    recovery: {
      answer_ask: "回答待处理的问题。",
      edit_input: "编辑当前输入。",
      export_diagnostics: "导出已脱敏的诊断包。",
      none: "没有可用的恢复操作。",
      open_audit: "查看审计证据。",
      open_settings: "配置本地 provider 设置。",
      refresh_snapshot: "完成配置变更后重试。",
      retry_command: "完成配置变更后重试。",
      retry_task: "重试受影响的任务。",
      wait_for_events: "等待 sidecar 事件后再重试。",
    },
  },
  workspace: {
    actions: {
      openOrAddWorkspace: "打开或添加工作区",
    },
    labels: {
      workspace: "工作区",
      workspaces: "工作区",
    },
  },
  workspaceInspection: {
    actions: {
      openFile: "打开文件",
      refresh: "刷新",
      return: "返回",
      viewDiff: "查看 Diff",
    },
    labels: {
      captured: "已捕获",
      changed: "变更",
      changedFiles: "变更文件",
      clean: "干净",
      diff: "Diff",
      fileContent: "文件内容",
      file: "文件",
      fileDiff: "文件 Diff",
      fileViewer: "文件查看器",
      gitStatus: "Git 状态",
      inspectionViews: "检查视图",
      live: "实时",
      mixed: "混合",
      repository: "仓库",
      staged: "已暂存",
      truncated: "已截断",
      unstaged: "未暂存",
      untracked: "未跟踪",
      workspaceInspection: "工作区检查",
    },
    states: {
      cleanBody: "此工作区没有变更文件。",
      diffUnavailable: ({ reason }) => `Diff 不可用：${reason}。`,
      diffUnavailableTitle: "Diff 不可用",
      fileUnavailable: ({ reason }) => `文件无法以文本形式渲染：${reason}。`,
      fileUnavailableTitle: "文件不可用",
      inspectionFailed: "工作区检查失败。",
      inspectionUnavailable: "检查不可用",
      inspectionRouteUnavailable: "检查路由不可用",
      inspectionRouteUnavailableBody: "此路由缺少检查上下文。",
      loading: "正在加载工作区检查结果",
      readOnly: "只读工作区检查。",
      requiresSidecar: "工作区检查需要本地 sidecar。",
      statusUnavailable: "状态不可用。",
    },
  },
};
